[project]
name = "learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.12.8",
    "dagster-webserver>=1.12.8",
    "evidently>=0.7.18",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "dagsterBasics"
# This tells dg to look for 'defs' inside session2.py
code_location_target_module = "dagsterBasics.session2"
