name: MLOps Pipeline CI

on:
  push:
    branches: ["main"]

# 1. PERMISSIONS: Give the robot keys to the warehouse
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # <--- Crucial: Allows uploading to GHCR

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # 2. LOG IN: The robot signs into the registry
      # GITHUB_TOKEN is a magic password GitHub creates automatically.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. BUILD & PUSH: Build the box and ship it
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
